CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  login VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  secure BOOLEAN DEFAULT false,
  code VARCHAR(10)
);
